import os

ICONS_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "icons")
DB_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "databases")
EXPENSES_ICON = os.path.join(ICONS_PATH, "expenses.png")
ADD_ICON = os.path.join(ICONS_PATH, "add.png")
REMOVE_ICON = os.path.join(ICONS_PATH, "remove.png")
EXIT_ICON = os.path.join(ICONS_PATH, "exit.png")
SPLASH_SCREEN_IMAGE = os.path.join(ICONS_PATH, "expense_jar.png")
RUPEE_ICON = os.path.join(ICONS_PATH, "rupee.png")
DOLLAR_ICON = os.path.join(ICONS_PATH, "dollar.png")
EURO_ICON = os.path.join(ICONS_PATH, "euro.png")
BRITISH_POUND_ICON = os.path.join(ICONS_PATH, "british_pound.png")
JAPANESE_YEN_ICON = os.path.join(ICONS_PATH, "japanese_yen.png")
ABOUT_ICON = os.path.join(ICONS_PATH, "about.png")
CONTACT_ICON = os.path.join(ICONS_PATH, "contact.png")
BAR_GRAPH_ICON = os.path.join(ICONS_PATH, "bar_graph.png")
PIE_CHART_ICON = os.path.join(ICONS_PATH, "pie_chart.png")
LINE_GRAPH_ICON = os.path.join(ICONS_PATH, "line_graph.png")
EDIT_EXPENSE_WINDOW_ICON = os.path.join(ICONS_PATH, "edit_window.png")
EDIT_BUTTON_ICON = os.path.join(ICONS_PATH, "edit_button.png")
CANCEL_ICON = os.path.join(ICONS_PATH, "cancel.png")
DATABASE = f"sqlite:///{DB_PATH}/expense_jar_db.sqlite"
